    $(function(){
        $("#header").load("/SV-Website/standard/header.html");
    });
    $(function(){
        $("#footer").load("/SV-Website/standard/footer.html");
    });
    $(function(){
        $("#copyright").load("/SV-Website/standard/copyright.html");
    });
    $(function(){
        $("#bestellinfo").load("/SV-Website/standard/bestellinfo.html");
    });